AWSTemplateFormatVersion: "2010-09-09"
Description: "Code for Lambda Role"
Parameters:
  ServiceName:
    Type: String
    Default: daochat

Resources:
  LambdaRole:
    Type: "AWS::IAM::Role"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      RoleName: !Sub "${ServiceName}-lambda-role"
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: !Sub "${ServiceName}-lambda-role"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
          - Effect: Allow
            Resource: "*"
            Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:Query'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:PutItem'
          - Effect: Allow
            Resource: "*"
            Action:
              - "cognito-identity:Get*"
              - "cognito-identity:List*"
              - "cognito-idp:AdminGet*"
              - "cognito-idp:AdminList*"
              - "cognito-idp:List*"
              - "cognito-idp:Get*"
              - "secretsmanager:*"

Outputs:
  FunctionRoleArn:
    Value: !GetAtt LambdaRole.Arn