AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda"
Parameters:
  ServiceName:
    Type: String
    Default: daochat

Resources:
  Lambda-Role:
    Type: "AWS::IAM::Role"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      RoleName: !Sub "${ServiceName}-lambda-role"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub "${ServiceName}-lambda-role"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource: "*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents

  admin-api:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Code:
        ZipFile:
          "index.handler"
  chat-api:

  todo-api:

  user-api:

  wallet_login_create_auth_callenge:

  wallet_login_define_auth_challenge:

  wallet_login_pre_signup:

  wallet_login_verify_auth_challenge: