AWSTemplateFormatVersion: "2010-09-09"
Description: "Code for JWT SecretManager"
Parameters:
  ServiceName:
    Type: String
    Default: daochat

Resources:
  CloudFormationCreatedSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: "JWT用SM"
      Name: !Sub "${ServiceName}-JWT-SECRET"